Repository Monreseauapp/app-back, pull requests merged in 2025-07, with the labels that each got.

#4 feat: add CI/CD workflows for backend, including branch protection and PR size checks
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/backend-ci.yml
  .github/workflows/branch-protection.yml
  .github/workflows/code-quality.yml
  .prettierrc
  eslint.config.mjs
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  test/app.e2e-spec.ts
Labels: size: M

#42 Fix/prod
  .github/workflows/code-quality.yml
  src/main.ts
  src/upload/upload.controller.ts
  src/upload/upload.service.ts
Labels: size: XS, risk: low

#43 Develop
  .github/workflows/code-quality.yml
  .github/workflows/deploy.yml
  src/main.ts
  src/upload/upload.controller.ts
  src/upload/upload.service.ts
  todo.md
Labels: risk: low, size: S

#48 feat: Added auth and double auth
  data.sql
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/strategies/jwt.strategy.ts
  src/company/company.controller.ts
  src/decorators/auth.decorator.ts
  src/job-domain/job-domain.controller.ts
  src/main.ts
  src/upload/upload.controller.ts
  src/users/users.controller.ts
  src/users/users.module.ts
Labels: size: L, risk: medium

#51 Fix/merge
  src/main.ts
  src/upload/upload.controller.ts
Labels: size: XS, risk: low

#54 Develop
  data.sql
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.controller.spec.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/strategies/jwt.strategy.ts
  src/company/company.controller.ts
  src/decorators/auth.decorator.ts
  src/job-domain/job-domain.controller.ts
  src/main.ts
  src/upload/upload.controller.ts
  src/users/users.controller.ts
  src/users/users.module.ts
Labels: size: XL, risk: high

#55 Fix/prod
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.controller.ts
  src/auth/auth.guard.ts
  src/common/decorators/api-key.decorator.ts
  src/common/decorators/auth.decorator.ts
  src/common/guards/api-key.guard.ts
  src/company/company.controller.ts
  src/job-domain/job-domain.controller.ts
  src/main.ts
  src/upload/upload.controller.ts
  src/users/users.controller.ts
Labels: size: XL, risk: high

#61 Merge/fix/develop
  package-lock.json
  package.json
  src/common/guards/api-key.guard.ts
Labels: risk: low, size: S

#62 Develop
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/app.controller.ts
  src/common/guards/api-key.guard.ts
Labels: size: M, risk: low

#64 fix/prod
  .github/workflows/deploy.yml
  package-lock.json
  src/app.controller.ts
Labels: risk: low, size: S

#69 Fix/prod
  package-lock.json
  src/common/guards/api-key.guard.ts
  src/main.ts
Labels: risk: low, size: S

#77 Feat/readme
  README.md
  package-lock.json
  package.json
  src/common/guards/api-key.guard.ts
Labels: risk: low, size: S

#78 Feat/stripe
  nest-cli.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.guard.ts
  src/common/guards/api-key.guard.ts
  src/company/company.controller.ts
  src/company/company.module.ts
  src/company/company.service.ts
  src/main.ts
  src/recommandation/recommandation.controller.ts
  src/recommandation/recommandation.service.ts
  src/stripe/stripe.controller.ts
  src/stripe/stripe.module.ts
  src/stripe/stripe.service.ts
  src/subscription/subscription.controller.ts
  src/subscription/subscription.service.ts
Labels: size: XL, risk: high

#79 Develop
  README.md
  nest-cli.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.controller.ts
  src/app.module.ts
  src/auth/auth.guard.ts
  src/company/company.controller.ts
  src/company/company.module.ts
  src/company/company.service.ts
  src/main.ts
  src/recommandation/recommandation.controller.ts
  src/recommandation/recommandation.service.ts
  src/stripe/stripe.controller.ts
  src/stripe/stripe.module.ts
  src/stripe/stripe.service.ts
  src/subscription/subscription.controller.ts
  src/subscription/subscription.service.ts
Labels: size: XL, risk: high

#81 Develop
  package-lock.json
  src/app.module.ts
  src/auth/auth.guard.ts
  src/common/guards/api-key.guard.ts
  src/email/email.controller.spec.ts
  src/email/email.controller.ts
  src/email/email.module.ts
  src/email/email.service.spec.ts
  src/email/email.service.ts
  src/email/templates/welcome.hbs
  src/main.ts
Labels: size: L, risk: medium

#82 feat: change database and add table for form and run lint + format
  prisma/schema.prisma
  src/company/company.service.ts
  src/email/email.module.ts
  src/email/email.service.ts
  src/recommandation/recommandation.service.ts
  src/stripe/stripe.controller.ts
Labels: size: XS, risk: low

#87 Feat/reco
  src/recommandation/recommandation.service.ts
  src/users/users.service.ts
Labels: size: XS, risk: low
